name: update

on:
  push:

  schedule:
    # Run at 12:00 JST 
    - cron: '0 3 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install dependencies
        run: |
          pip install -U pip setuptools tox wheel twine

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: ./bin/ci/deploy
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}